---
title: "Notes"
author: "ADam"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Elaborations on the GAMYE

### Goals

1.  Describe the spatial hierarchical version of a GAMYE

2.  Consider if it's worth the effort to demonstrate the similarity of the alternative parameterisations of the hierarchical structure

    1.  hierarchical beta-terms (similar to Smith and Edwards 2020)

    2.  Global and local smooths (similar to Pedersen et al. 2020)

3.  Fake data simulation to demonstrate accuracy

    1.  generate a balanced dataset with observations for all routes and all years, using the realised observer allocations.

        1.  smooth trajectory - model is correct

            1.  vary the betas using the neighbourhood relationships and a known sd_beta

            2.  calculate the realised mean betas

            3.  generate the true trajectories for each stratum and the overall mean trajectory

                1.  plot them to confirm

            4.  Confirm that the following parameters are accurately estimated:

                1.  BETAs

                2.  betas

                3.  Mean trajectory

                4.  stratum trajectories

                5.  year-effects

        2.  False Model

            1.  same as above, but with non-spatial variation in trajectories - mean trajectory and random variation among strata - using Cerulean Warbler...

        3.  Simple trajectory with same year-effects across all strata - shorebird structural demo

            1.  do same as above, but with hierarchical year-effects that have little variation among strata

        4.  linear trend - same as above, but with only one BETA != 0

        5.  breakpoint - same as above, but with only one (or two) BETA != 0

        6.  

4.  Test-cases: conduct 10-fold CV in each case (compare to non-spatial version).

    1.  BBS

        1.  spatial structure on abundance and smooth

        2.  True observer effects (small mention, but in reality trivial, it's not an elaboration, this is a correction of a patently false ad-hoc structure)

    2.  CBC

        1.  additional effort parameters, which may also vary in space?

    3.  Shorebirds

        1.  additional seasonal parameters

        2.  alternative year-effects and summary trajectory
